# Generated by Django 5.0.10 on 2026-01-08 16:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eliminado"
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=200, verbose_name="Razón Social"),
                ),
                (
                    "nombre_fantasia",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre de Fantasía"
                    ),
                ),
                (
                    "cuit",
                    models.CharField(max_length=13, unique=True, verbose_name="CUIT"),
                ),
                (
                    "tipo_proveedor",
                    models.CharField(
                        choices=[
                            ("NACIONAL", "Nacional"),
                            ("INTERNACIONAL", "Internacional"),
                        ],
                        default="NACIONAL",
                        max_length=20,
                        verbose_name="Tipo de Proveedor",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ingrese un número de teléfono válido",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                ("sitio_web", models.URLField(blank=True, verbose_name="Sitio Web")),
                ("calle", models.CharField(max_length=100, verbose_name="Calle")),
                ("numero", models.CharField(max_length=10, verbose_name="Número")),
                (
                    "piso",
                    models.CharField(blank=True, max_length=10, verbose_name="Piso"),
                ),
                (
                    "localidad",
                    models.CharField(max_length=100, verbose_name="Localidad"),
                ),
                (
                    "provincia",
                    models.CharField(max_length=100, verbose_name="Provincia"),
                ),
                (
                    "codigo_postal",
                    models.CharField(max_length=10, verbose_name="Código Postal"),
                ),
                (
                    "pais",
                    models.CharField(
                        default="Argentina", max_length=100, verbose_name="País"
                    ),
                ),
                (
                    "condiciones_pago",
                    models.CharField(
                        help_text="Ejemplo: 30/60/90 días",
                        max_length=200,
                        verbose_name="Condiciones de Pago",
                    ),
                ),
                (
                    "descuento_pronto_pago",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Descuento Pronto Pago (%)",
                    ),
                ),
                (
                    "plazo_entrega_dias",
                    models.IntegerField(
                        default=0, verbose_name="Plazo de Entrega (días)"
                    ),
                ),
                (
                    "contacto_nombre",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contacto - Nombre"
                    ),
                ),
                (
                    "contacto_telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Contacto - Teléfono"
                    ),
                ),
                (
                    "contacto_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contacto - Email"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["razon_social"],
                "indexes": [
                    models.Index(fields=["cuit"], name="proveedores_cuit_dd0c99_idx"),
                    models.Index(
                        fields=["razon_social"], name="proveedores_razon_s_7bec47_idx"
                    ),
                ],
            },
        ),
    ]
