# Generated by Django 4.1.3 on 2024-05-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra_clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
