# Generated by Django 5.0.10 on 2026-01-08 16:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eliminado"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("CUIT", "CUIT"),
                            ("CUIL", "CUIL"),
                            ("PASAPORTE", "Pasaporte"),
                        ],
                        default="DNI",
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Documento"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ingrese un número de teléfono válido",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                ("calle", models.CharField(max_length=100, verbose_name="Calle")),
                ("numero", models.CharField(max_length=10, verbose_name="Número")),
                (
                    "piso",
                    models.CharField(blank=True, max_length=10, verbose_name="Piso"),
                ),
                (
                    "departamento",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Departamento"
                    ),
                ),
                (
                    "localidad",
                    models.CharField(max_length=100, verbose_name="Localidad"),
                ),
                (
                    "provincia",
                    models.CharField(max_length=100, verbose_name="Provincia"),
                ),
                (
                    "codigo_postal",
                    models.CharField(max_length=10, verbose_name="Código Postal"),
                ),
                (
                    "pais",
                    models.CharField(
                        default="Argentina", max_length=100, verbose_name="País"
                    ),
                ),
                (
                    "tipo_cliente",
                    models.CharField(
                        choices=[
                            ("MINORISTA", "Minorista"),
                            ("MAYORISTA", "Mayorista"),
                            ("VIP", "VIP"),
                        ],
                        default="MINORISTA",
                        max_length=20,
                        verbose_name="Tipo de Cliente",
                    ),
                ),
                (
                    "limite_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Límite de Crédito",
                    ),
                ),
                (
                    "saldo_actual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Saldo Actual",
                    ),
                ),
                (
                    "descuento_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Descuento (%)",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["numero_documento"],
                        name="clientes_cl_numero__868cb7_idx",
                    ),
                    models.Index(fields=["email"], name="clientes_cl_email_eae461_idx"),
                    models.Index(
                        fields=["apellido", "nombre"],
                        name="clientes_cl_apellid_894bd6_idx",
                    ),
                ],
            },
        ),
    ]
